# This is Ingress controller file
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-controller
spec:
 rules:
  - host: my-app.example.com
    http:
      paths:
        - path: /app
          pathType: Prefix
          backend:
            service:
              name: my-app-service
              port: 
                number: 80