## YAML Manifest for a K8s Secret
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4=  # Base64 encoded "admin"
  password: MWYyZDFlMmU2N2Rm  # Base64 encoded "1f2d1e2e67df"

