
- name: Basic ansible playbook
  hosts: your_target_hosts
  tasks:
    - name: Install apache
      become: yes 
      apt:
        name: apache2
        state: present
    - name: ensure apache is running
      become: yes 
      service: 
        name: apache2
        state: started

  